### ISSUE TITLE
Mislabeled amendment 13 as 12 and 18 as 17 in history

### ISSUE THREAD

**Issue by howonlee** [JesseKPhillips/USA-Constitution#1]
Happy force pushing, I guess

**Comment by arnemahl** [comment]
Is 18 also labeled as 17? Something about "III" 🤔

**Comment by JesseKPhillips** [comment]
Yeah, I also didn't know of all the tools to fix this, I suppose it is a good time to correct mistakes with a force push and do it right. Thanks for identifying where they are.

**Comment by JesseKPhillips** [comment]
have a branch rewrite/history which fixes this issue, at some point it will replace current master.
