### ISSUE TITLE
Record voting details in git commit message

### ISSUE THREAD

**Issue by InnovativeInventor** [JesseKPhillips/USA-Constitution#12]
The margins of the votes, the states which ratified the amendments (as well as metadata, such as when) should be included in the git commit messages.

**Comment by JesseKPhillips** [comment]
Could I get some help on this. I'm going to do a one time history rewrite to address some mistakes. If you could get these details and do multiple squash commits in a branch, it would go faster.

`git commit --squash <hash>`

The commit message would include the additional details of interest.  Sorry you'd lose authorship of the work, but think is for the best.

**Comment by JesseKPhillips** [comment]
Nevermind, I think I can put it together and wouldn't wan to have duplicate work.

**Comment by JesseKPhillips** [comment]
Actually, I this 'notes' might be a better place for this. Tools aren't as good with them, but I think that they fit better there.

**Comment by varenc** [comment]
GitHub doesn't actually support displaying git-notes right? If that's true than IMHO attaching the voting info to the commit log would be best.

(git notes do have the amazing feature of giving you mutable extra data on an immutable commit history...but hopefully, you can just do one great force pushed history rewrite and leave at that until the next constitutional amendment comes around)

**Comment by InnovativeInventor** [comment]
@varenc I think visibility in GitHub is important (not many people are going to clone this repo and check out the git notes). Another way would be to reference a mutable document/issue/pull request and have the "discussion"/posting/citing of reference materials (for example, the federalist papers) happen there. These "discussions" could also be locked/edited at any time.

**Comment by JesseKPhillips** [comment]
This is done in the rewrite with Wikipedia info (and citation). I have not decided if I will go back and adjust the formatting.
