### ISSUE TITLE
Confusing explanation of commit dates

### ISSUE THREAD

**Issue by cpcallen** [JesseKPhillips/USA-Constitution#14]
I've now read this explanation several times:

> With the exception of the commits made in 1971, the year was actually 1791, I follow the simple path of ignoring the least significant digit. So 1996 means 196?as I chop off the 19, the year 1000 is implied and then tack on the next two significant digits of the year which is 96 and leaves off the specific year.

…but I am still no closer to understanding the date mapping than I was to begin with.  Maybe a mathematical formula or list of examples might help?

**Comment by Hoaas** [comment]
(year - 1800) + "x" I think?

1980 -> 180x
1985 -> 185x
1995 -> 195x
1996 -> 196x

**Comment by JesseKPhillips** [comment]
Thanks, I agree. It really isn't useful because the specific year is lost.

**Comment by JesseKPhillips** [comment]
Tried to make it clear through an example.
