### ISSUE TITLE
Create Code

### ISSUE THREAD

**Issue by mm-s** [JesseKPhillips/USA-Constitution#15]
Translating this set of rules written in English to executable code is challenging, but should be undertaken.
Any motivation around to design an automated law system?
Thanks

**Comment by mm-s** [comment]
Love the label : )

**Comment by codrcodz** [comment]
In all seriousness though... certain aspects could be pretty neatly captured with an object-oriented model of the entities involved here. If each power holder (i.e. the states, the federal branches of government,  the people, etc.) were different objects and powers were methods, you could probably at least show checks and balances pretty effectively.
