### ISSUE TITLE
"Add .editorconfig" breaks git blame for Constitution.md

### ISSUE THREAD

**Issue by kachkaev** [JesseKPhillips/USA-Constitution#19]
I'm wondering if commits in the repo could be re-built from scratch because of 73b7f743ebc65549b1a9b5c62415e453f7ccd08b. Otherwise, here is what we see in [`git blame` for `Constitution.md`](https://github.com/JesseKPhillips/USA-Constitution/blame/master/Constitution.md):

![Screenshot 2020-02-17 at 19 04 11](https://user-images.githubusercontent.com/608862/74680412-74955f00-51b8-11ea-9e1c-90dd001daf37.png)

Not as pure as could be. Hope the change is easy to automate.

**Comment by JesseKPhillips** [comment]
I'm not too worried about this, you can always blame an earlier commit:
https://github.com/JesseKPhillips/USA-Constitution/blame/9956c5f1b9a91f26da57e06dc3c0beb37692ba9d/Constitution.md

which is ultimately something needed as edits are made.
