### ISSUE TITLE
Article 1 Section 8 is missing

### ISSUE THREAD

**Issue by alex996** [JesseKPhillips/USA-Constitution#20]
Thanks for your work putting this together. Perhaps more of a question, but I don't see Article. I. Section. 8. in [Constitution.md](https://github.com/JesseKPhillips/USA-Constitution/blob/master/Constitution.md). It's an important section that enumerates the powers of the Federal government. It can be found on [archives.org](https://www.archives.gov/founding-docs/constitution-transcript#toc-section-8-) and [congress.gov](https://constitution.congress.gov/constitution/) to name a few. Other sections seem to be missing content as well; for example Article. I. Section. 7. is missing Clause 3. Am I misreading something or Is this somehow connected? Cheers

**Comment by JesseKPhillips** [comment]
Looks like Article I is in twice and the second has section 8. I'll need to fix that.
