### ISSUE TITLE
Amendments should not appear in main body of Constitution.md

### ISSUE THREAD

**Issue by winnkoster** [JesseKPhillips/USA-Constitution#24]
I noticed that many of the amendment commits add text to the main body of `Constitution.md` in addition to adding a file for each amendment (eg: the [commit for Amendment XXI](https://github.com/JesseKPhillips/USA-Constitution/commit/998404b8e7f58f47007f0c284b2f81ac756aa4c5) includes both a new file with the amendment, `amendments/00021.md`, and also an edit to `Constitution.md`). However, the edit to the main body of `Constitution.md` is not real and should not be included.

As I looked into this further, I noticed that many amendments were erroneously scattered throughout the main text of `Constitution.md` in seemingly random (and incorrect) places. Here are some more examples I found in a quick skim:
- The text of [Amendment I](https://www.constituteproject.org/constitution/United_States_of_America_1992#s139) is included in Article I Section 1 of `Constitution.md` (see [line 15](https://github.com/JesseKPhillips/USA-Constitution/blob/master/Constitution.md?plain=1#L15)) but it should not be (see true US Constitution [text](https://www.constituteproject.org/constitution/United_States_of_America_1992#s5) for Article I Section 1)
  - This change appears to have occurred during the [Bill of Rights commit](https://github.com/JesseKPhillips/USA-Constitution/commit/a51cdaaf6b7a75d8b804c35ca0ecd185c7ab51e5), prior to this the text was accurate
- The text of [Amendment III](https://www.constituteproject.org/constitution/United_States_of_America_1992#s143) is included in Article II Section 2 of `Constitution.md` (see [line 496](https://github.com/JesseKPhillips/USA-Constitution/blob/master/Constitution.md?plain=1#L496)) but it should not be (see true US Constitution [text](https://www.constituteproject.org/constitution/United_States_of_America_1992#s78) for Article II Section 2)
  - This change appears to have occurred during the [Bill of Rights commit](https://github.com/JesseKPhillips/USA-Constitution/commit/a51cdaaf6b7a75d8b804c35ca0ecd185c7ab51e5), prior to this the text was accurate
- The text of Amendments [IV](https://www.constituteproject.org/constitution/United_States_of_America_1992#s145), [V](https://www.constituteproject.org/constitution/United_States_of_America_1992#s147), [VI](https://www.constituteproject.org/constitution/United_States_of_America_1992#s149), [VII](https://www.constituteproject.org/constitution/United_States_of_America_1992#s151), and [VIII](https://www.constituteproject.org/constitution/United_States_of_America_1992#s153) appear in Article III Section 4 of `Constitution.md` but in reality there is no Article III Section 4 of the US Constitution (see [link](https://www.constituteproject.org/constitution/United_States_of_America_1992#s86) to the top of Article III)
  - This change appears to have occurred during the [Bill of Rights commit](https://github.com/JesseKPhillips/USA-Constitution/commit/a51cdaaf6b7a75d8b804c35ca0ecd185c7ab51e5), prior to this the text was accurate
- A portion of the text of [Amendment XVIII](https://www.constituteproject.org/constitution/United_States_of_America_1992#s191) is included in Article VIII of `Constitution.md` (see [line 724](https://github.com/JesseKPhillips/USA-Constitution/blob/master/Constitution.md?plain=1#L724)) but in reality there is no Article VIII of the US Constitution (see [link](https://www.constituteproject.org/constitution/United_States_of_America_1992#s114) to Article VII, which is the last article before amendments)
- I also observed some major textual discrepancies between the `Constitution.md` Article I Sections 1 and 2 and the true version. It looks to me like there may have been some git rebase/squash/force related issues, because early commits of these repo have the correct text, but later commits ([this one](https://github.com/JesseKPhillips/USA-Constitution/commit/fde803d2fa0c4b1c971cd942254ad20f21ebff22), for example) seem to alter the text in unexpected ways

I consulted the following three sources for the text of the US Constitution and they all agree that the examples I provide above are erroneous.
- https://constitution.congress.gov/constitution/
- https://www.constituteproject.org/constitution/United_States_of_America_1992
- https://constitutioncenter.org/interactive-constitution/full-text

There may be more errors; I didn't dig too deeply into this. If you like, I'm happy to clone the repo and open a pull request with all the errors I could find, although I didn't want to just randomly open a PR on your repo without hearing from you first. Let me know, and thank you for putting so much work into this. It's a very cool project!

**Comment by JesseKPhillips** [comment]
Thank you for your detailed review, unfortunately that is the entire point of this repository. Amendments are textual changes to the body of the document, legally the original document and amendments are preserved separately. The Readme states

"The United States of America's Constitution has seen many modifications over the centuries. These changes have been handled without modification of the original document through what is called an Amendment. But what does the final document look like? How did these Amendments actually change what that document said? This repository answers those questions, to the best of my ability."

You mention that the edits seem to be random and incorrect, if the edit are in fact incorrect and don't match the amendment, those are definitely of interest. Note that in some situations it my be more opinion than fact E.g the Article VIII
