### ISSUE TITLE
Amendment XII Typo (in title)

### ISSUE THREAD

**Issue by j6k4m8** [JesseKPhillips/USA-Constitution#4]
See pointer below; "Amendment" is misspelled "Amendemnt".

https://github.com/JesseKPhillips/USA-Constitution/blame/master/amendments.md#L7

**Comment by JesseKPhillips** [comment]
This is addressed in the rewrite/history branch.

Thank you.

**Comment by j6k4m8** [comment]
Awesome! Great project!
