### ISSUE TITLE
Potentially overly centralized, but interesting.

### ISSUE THREAD

**Issue by hitchhiker** [JesseKPhillips/USA-Constitution#6]
Regarding "We the People" 0ab6fd623757e034e86d87df07efaa38626f765e - great effort, genuinely lovely idea. 

I would suggest that these entities "Senate" and "House of Representatives" seem to have extraordinarily elevated permissions. I understand you intend them to marshall resources, allocate permissions on behalf of "The People" but what's to stop a runaway condition, an accumulation of power? This is essentially a classical centralized heirarchy. 

Your intention to create a "more perfect Union" is noble, but what's to guarentee "The People" will ultimately retain any form of representation in this structure? A reasonably well organized attack on any of the principal nodes (or inter-process comms) would result in the entire system being overwhelmed and overrun by malicious actors (with or without local permissions). "The People" would become subserviant to this system - IMHO it's just not going to remain distributed in the way you are intending. 

Time will tell. Not convinced, perhaps you need to decentralize more. gl hf!

**Comment by JesseKPhillips** [comment]
If you can specify specific improvements then additional evaluation can be done to decentralize. Congressional bills welcome.
